name: GitHub Actions Build and Deploy Demo

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: macos

    steps:
      - name: checkout

        uses: actions/checkout@master

        # 安装依赖

      - name: install

        run: npm install

        # 打包构建

      - name: build

        run: npm run build

        # 部署运行

      - name: Deploy

        uses: JamesIves/github-pages-deploy-action@v4.3.0

        with:
          ACCESS_TOKEN: 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

          BRANCH: master

          FOLDER: build
